name = "edus-trader"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "edus-trader-db"
database_id = "6a751f5f-78bd-4e59-97bb-b149c63c7230"

[vars]
ENVIRONMENT = "production"
APP_URL = "https://edustrader.pages.dev"
